'use client';

import { SymptomAnalysisOutput } from "@/ai/flows/symptom-analysis";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { CheckCircle, AlertTriangle, Info, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";

interface ConditionDisplayProps {
  conditions: SymptomAnalysisOutput;
  name: string;
  age: string;
  gender: string;
  email: string;
  symptoms: string;
  medicalHistory: string;
  questions: string[];
  answers: string[];
}

export const ConditionDisplay: React.FC<ConditionDisplayProps> = ({
  conditions,
  name,
  age,
  gender,
  email,
  symptoms,
  medicalHistory,
  questions,
  answers,
}) => {
  const getIcon = (likelihood: number) => {
    if (likelihood > 0.75) {
      return <CheckCircle className="w-4 h-4 text-green-500 mr-1" />;
    } else if (likelihood > 0.5) {
      return <AlertTriangle className="w-4 h-4 text-yellow-500 mr-1" />;
    } else {
      return <Info className="w-4 h-4 text-gray-500 mr-1" />;
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Cover Page
    doc.setFontSize(24);
    doc.text("ManoMed AI - Medical Analysis Report", pageWidth / 2, y, { align: "center" });
    y += 20;
    doc.setFontSize(12);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, y, { align: "center" });
    doc.addPage();

    // Table of Contents
    doc.setFontSize(18);
    doc.text("Table of Contents", margin, y);
    y += 15;
    doc.setFontSize(12);
    doc.text("1. Patient Information", margin, y);
    y += 10;
    doc.text("2. Symptoms and Medical History", margin, y);
    y += 10;
    doc.text("3. Questionnaire Responses", margin, y);
    y += 10;
    doc.text("4. Analysis Results", margin, y);
    doc.addPage();

    // Patient Information
    y = 20;
    doc.setFontSize(16);
    doc.text("1. Patient Information", margin, y);
    y += 15;
    doc.setFontSize(12);
    doc.text(`Name: ${name}`, margin, y);
    y += 10;
    doc.text(`Age: ${age}`, margin, y);
    y += 10;
    doc.text(`Gender: ${gender}`, margin, y);
    y += 10;
    doc.text(`Email: ${email}`, margin, y);
    doc.addPage();

    // Symptoms and Medical History
    y = 20;
    doc.setFontSize(16);
    doc.text("2. Symptoms and Medical History", margin, y);
    y += 15;
    doc.setFontSize(12);
    doc.text("Reported Symptoms:", margin, y);
    y += 10;
    const symptomsLines = doc.splitTextToSize(symptoms, pageWidth - 2 * margin);
    doc.text(symptomsLines, margin, y);
    y += symptomsLines.length * 7 + 10;
    doc.text("Medical History:", margin, y);
    y += 10;
    const historyLines = doc.splitTextToSize(medicalHistory || "None provided", pageWidth - 2 * margin);
    doc.text(historyLines, margin, y);
    doc.addPage();

    // Questionnaire Responses
    y = 20;
    doc.setFontSize(16);
    doc.text("3. Questionnaire Responses", margin, y);
    y += 15;
    doc.setFontSize(12);
    questions.forEach((question, index) => {
      if (y > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        y = 20;
      }
      doc.text(`Q${index + 1}: ${question}`, margin, y);
      y += 10;
      doc.text(`A${index + 1}: ${answers[index] || "No answer provided"}`, margin, y);
      y += 15;
    });
    doc.addPage();

    // Analysis Results
    y = 20;
    doc.setFontSize(16);
    doc.text("4. Analysis Results", margin, y);
    y += 15;
    doc.setFontSize(12);
    conditions.forEach((condition, index) => {
      if (y > doc.internal.pageSize.getHeight() - 60) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(14);
      doc.text(`${index + 1}. ${condition.condition}`, margin, y);
      y += 10;
      doc.setFontSize(12);
      doc.text(`Likelihood: ${(condition.likelihood * 100).toFixed(2)}%`, margin, y);
      y += 10;
      const descriptionLines = doc.splitTextToSize(condition.description || "No description available.", pageWidth - 2 * margin);
      doc.text(descriptionLines, margin, y);
      y += descriptionLines.length * 7 + 10;
    });

    // Disclaimer
    doc.addPage();
    y = 20;
    doc.setFontSize(14);
    doc.text("Disclaimer", margin, y);
    y += 15;
    doc.setFontSize(12);
    const disclaimerText = "This report is generated by ManoMed AI and is not a substitute for professional medical advice. Always consult with a qualified healthcare provider for diagnosis and treatment.";
    const disclaimerLines = doc.splitTextToSize(disclaimerText, pageWidth - 2 * margin);
    doc.text(disclaimerLines, margin, y);

    doc.save("manomed-ai-report.pdf");
  };

  return (
    <div>
      <h2 className="text-xl font-semibold mb-4 text-primary">Potential Conditions</h2>
      {conditions.length > 0 ? (
        <>
          <div className="grid gap-6">
            {conditions.map((condition, index) => (
              <Card key={index} className="shadow-md rounded-2xl">
                <CardHeader>
                  <CardTitle className="flex items-center">
                    {condition.condition}
                  </CardTitle>
                  <CardDescription>
                    Likelihood:
                    <Badge variant="secondary" className="ml-1">
                      {(condition.likelihood * 100).toFixed(2)}%
                    </Badge>
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center mb-2">
                    {getIcon(condition.likelihood)}
                    <span className="ml-1">
                      {condition.description || "No description available."}
                    </span>
                  </div>
                  <Button
                    variant="link"
                    className="text-sm p-0 mt-2"
                    onClick={() =>
                      window.open(
                        `https://www.webmd.com/search/search_results/default.aspx?query=${encodeURIComponent(condition.condition)}`,
                        "_blank"
                      )
                    }
                  >
                    Learn more on WebMD →
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>

          <div className="flex justify-center mt-8">
            <Button onClick={generatePDF} className="flex items-center gap-2">
              <Download className="w-4 h-4" />
              Download Complete Report (PDF)
            </Button>
          </div>
        </>
      ) : (
        <p>No potential conditions found.</p>
      )}
    </div>
  );
};
