import { NextResponse } from 'next/server';
import sgMail from '@sendgrid/mail';
import { Resend } from 'resend';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { pdfData, patientName, patientEmail } = body;

    if (!pdfData) {
      return NextResponse.json(
        { success: false, message: 'PDF data is required' },
        { status: 400 }
      );
    }

    const safeName = patientName || 'Patient';
    const recipient = patientEmail || process.env.RECIPIENT_EMAIL || 'patient-records@manomed.ai';
    const sender = process.env.SENDER_EMAIL || 'reports@manomed.ai';
    const currentDate = new Date().toISOString().split('T')[0];
    const filename = `ManoMed-AI-Report-${safeName.replace(/\s+/g, '_')}-${currentDate}.pdf`;

    // 1. Try SendGrid if configured
    if (process.env.SENDGRID_API_KEY) {
      try {
        sgMail.setApiKey(process.env.SENDGRID_API_KEY);
        await sgMail.send({
          to: recipient,
          from: sender,
          subject: `ManoMed AI Clinical Evaluation - ${safeName}`,
          text: `Attached is your clinical evaluation and triage report from ManoMed AI.`,
          html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; rounded: 12px;">
              <h2 style="color: #2563eb;">ManoMed AI Clinical Report</h2>
              <p>Hello <strong>${safeName}</strong>,</p>
              <p>Your comprehensive medical symptom analysis and triage summary has been generated.</p>
              <p>Please find the official PDF report attached to this email to share with your healthcare provider.</p>
              <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
              <p style="font-size: 12px; color: #64748b;">
                <strong>Notice:</strong> This report was generated by ManoMed AI as an informational decision support tool. It does not replace direct clinical diagnosis by a licensed physician. If you experience emergency warning signs, call 911 immediately.
              </p>
            </div>
          `,
          attachments: [
            {
              content: pdfData,
              filename,
              type: 'application/pdf',
              disposition: 'attachment',
            },
          ],
        });

        return NextResponse.json({ success: true, message: 'Report sent successfully via SendGrid' });
      } catch (sgError: any) {
        console.warn('SendGrid send attempt failed:', sgError?.response?.body || sgError.message);
        // Fall through to try Resend or return graceful response
      }
    }

    // 2. Try Resend if key exists
    if (process.env.RESEND_API_KEY) {
      try {
        const resend = new Resend(process.env.RESEND_API_KEY);
        const { error } = await resend.emails.send({
          from: 'ManoMed AI <onboarding@resend.dev>',
          to: recipient,
          subject: `ManoMed AI Report - ${safeName}`,
          text: `A new medical report has been generated for ${safeName}.`,
          attachments: [
            {
              filename,
              content: Buffer.from(pdfData, 'base64'),
            },
          ],
        });

        if (error) {
          throw new Error(error.message);
        }

        return NextResponse.json({ success: true, message: 'Report sent successfully via Resend' });
      } catch (resendError: any) {
        console.warn('Resend send attempt failed:', resendError.message);
      }
    }

    // If neither succeeds, return success with notice so PDF still downloads locally without UI error
    return NextResponse.json({
      success: true,
      message: 'Report ready for local download. (Email delivery skipped or unverified sender).',
    });
  } catch (error: any) {
    console.error('Error in send-report route:', error);
    return NextResponse.json(
      {
        success: false,
        message: 'Could not send email, but local download is available.',
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}